### ISSUE TITLE
Tighten Up Instagram Section

### ISSUE THREAD

**Issue by andandandandrew** [andandandandrew/HB-Site#6]
Via Adam:

*I’d like to make them closer to 15em x 15em and get one more on there, and maybe reduce the padding above and below to make the instagram section not quite so big.*

**Comment by andandandandrew** [comment]
I'm cool with that. The only problem that may happen is the text may overun the :hover states. Easy fix though.

**Comment by andandandandrew** [comment]
I am fixing this one now. Will be in style.css and maybe instafeed.js

**Comment by andandandandrew** [comment]
I've shrunk them and made the margins smaller. Personally I wouldn't mess with the padding/height of the instafeed section as it's consistent with the rest of the site. Your call. Also, I changed it to pull in 6 instead of 5—it just stays fluid easier.

**Comment by andandandandrew** [comment]
There is an image on there right now with way to much overlapping text. We can drop the font size, or I don't know if there's a character count on the instafeed we can set for the comments.

**Comment by adamreify** [comment]
I think it's fine. Most of them wont be that long.  If it becomes an issue I can re-address.
