### ISSUE TITLE
Home Page—Add Goldenrod to :hover on scrollstache

### ISSUE THREAD

**Issue by andandandandrew** [andandandandrew/HB-Site#7]

**Comment by andandandandrew** [comment]
need to create a sprite for this, add appropriate css, or go SVG. Adam, thoughts how you'd like it?

**Comment by adamreify** [comment]
That's fine homie.  Generally you can just go forward with whatever tech you want, as long as it will be halfway decent in older browsers.  I want this to be tech-forward and look super in modern browsers, and as long as it functions in IE i'm cool.

**Comment by andandandandrew** [comment]
right on. I've been using this too: http://outdatedbrowser.com/en

I use it on my site and personalized the message and styling, although you don't really need to. You can set it to basically what version of IE and below you want the "Upgrade IT" message loads.
