### ISSUE TITLE
Backup DB 5/3/15

### ISSUE THREAD

**Issue by andandandandrew** [andandandandrew/HB-Site#9]
**5/3/15 DB Backup**

I made a new folder in the wp_content folder called "_db-backups."

I put the backup XML file that Wordpress will export for you. I don't have access to the DB on the hosting side, so we should probably get a copy of the current SQL file to have as a backup here too.

**Comment by adamreify** [comment]
Is this going to be a problem that you don't have access?  I'm having trouble setting it up in GoDaddy to allow you access without giving you access to the whole account.  

I backed up the SQL file and will upload it.

**Comment by andandandandrew** [comment]
Nope! Just wanted a backup of the most recent one incase the internet implodes.
